
const Products = [
  {
    title: "T-SHIRT WITH TAPE DETAILS",
    id: 1,
    price: "$120",
    img_url: "/image 1.png",
    name: "T-SHIRT WITH TAPE DETAILS",
    img1: "/image 5.png",
    img2: "/image 5.png",
    img3: "/image 5.png",
    img4: "/image 5.png",
    color: ["blue", "black", "green"], 
    size: ["S", "M", "L", "XL"],
    unitPrice: 120,
    qty:1,
    description: "A stylish T-shirt featuring trendy tape details for a modern look.",
  },
  {
    title: "SKINNY FIT JEANS",
    id: 2,
    price: "$240",
    img_url: "/Frame 33.png",
    old_price: "$260",
    name: "SKINNY FIT JEANS",
    description: "Sleek and stylish skinny fit jeans for a sharp, modern look.",
    img1: "/Frame 33.png",
    img2: "/Frame 33.png",
    img3: "/Frame 33.png",
    img4: "/Frame 33.png",
    color: ["blue", "black", "green"], 
    size: ["S", "M", "L", "XL"],
    unitPrice: 240,
    qty:1,
  },
  {
    title: "CHECKERED SHIRT",
    id: 3,
    price: "$180",
    img_url: "/Frame 34.png",
    name: "CHECKERED SHIRT",
    description: "A classic checkered shirt that blends timeless style with comfort.",
    img1: "/Frame 34.png",
    img2: "/Frame 34.png",
    img3: "/Frame 34.png",
    img4: "/Frame 34.png",
    color: ["blue", "black", "green"], 
    size: ["S", "M", "L", "XL"],
    unitPrice: 180,
    qty:1,
  },
  {
    title: "SLEEVE STRIPED T-SHIRT",
    id: 4,
    price: "$130",
    img_url: "/Frame 38.png",
    old_price: "$160",
    name: "SLEEVE STRIPED T-SHIRT",
    description: "A trendy sleeve-striped T-shirt that adds a sporty touch to your outfit.",
    img1: "/Frame 38.png",
    img2: "/Frame 38.png",
    img3: "/Frame 38.png",
    img4: "/Frame 38.png",
    size: ["S", "M", "L", "XL"],
    unitPrice: 130,
    qty:1,
  },
];
export default Products
